language: java
script: cd api && mvn javadoc:jar package
deploy:
  provider: releases
  api_key:
    secure: Ux++pfw77VEgRXbgs0ZyyNE5HAwmjexr0L2ocsdr4D+/7Orhao4QrZnRz5DU8sJG49Z5A5mwFEQV+uJx07d6JPMPwVEZfoWcj4PKE2B2JNyckpBM8fo8LdgtqRmAo7dSWvscF6KjDEkI1a4Qo9Z8gY7gnoUdyQQ6+8ee4CXft6pFTYnPMohJ0nDRyEV5Eu6kKDSVa6gRM6T4FQHbWHfdFTfixIPkpbYVPNb1N4RMdLPpC666mFiSFPr08t4IyefA+9IumbhTW/M42yrOXRjDR3C77qT8aMMTLCOMU4d3ykXtsR3Fd3a4rJg2SnfaeJk0z46LY1CjAMH6IGFHftmqWlMKg76natVhbYs3y0kenYmC71GVlur/yyUn4enCxKXc/tswoJjrUrfINTdIHZjRo86o3jMAiBUhQ7IY6vB685jc8s1UjngjN8vXa5ff4QjL3y/HFYoCfI3/uRlNI4p5KCHcKTKP7GIhNpHtWNB8EhNEcwewP55z3ynh/ZUevWxH7ZwVusLldzfuW4HH4RtvKRqr2TBO1m6dFetjAmlJDv42dIGGoFv3SnA+yFEmH1oWINgLcu9DIoImIjYn24NmHkQjXe2Th79muUt2lwbLlplZXa8pNgro4o2aEak6RSkA1RBKk68h8ueby6408uHRwA7usUHtgHw0ZZ2do6cpAwQ=
  file: api/target/*.jar
  on:
    repo: cloudwatt/bssapi-sdk
